---
permalink: sg6000/upgrading-drive-firmware-using-auto-reboot.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, upgrade, firmware, drive, disk, automatic
summary: 'The StorageGRID Appliance Installer automatically installs the latest E-Series drive firmware files during appliance reboot.'
---
= Upgrade SG6000 drive firmware automatically during appliance reboot
:icons: font
:imagesdir: ../media/

[.lead]
The StorageGRID Appliance Installer automatically installs the latest E-Series drive firmware files during appliance reboot.

The latest E-Series drive firmware files are part of the StorageGRID Appliance Installer. These updates are install when the StorageGRID Appliance Installer reboots an appliance:

* From link:../installconfig/rebooting-appliance-while-sg-appliance-installer-is-running.html[maintenance mode] 
* As part of a link:../maintain/rolling-reboot-procedure.html[rolling reboot]
* During a link:../upgrade/performing-upgrade.html[StorageGRID version upgrade] or link:../maintain/applying-hotfix.html[hotfix installation]  
* During a link:../sg6000/upgrading-santricity-os-on-storage-controllers-using-maintenance-mode-sg6000.html[SANtricity OS upgrade]

NOTE:: While an appliance reboots, I/O (input/output) activity to the storage controller is stopped.

Upgrade status results and errors are in the `/var/log/symbol-rest.log` log file.
+
If needed, link:troubleshoot-upgrading-drive-firmware-using-santricity-system-manager.html[troubleshoot drive firmware upgrade errors].

You can also install drive firmware upgrades manually using the SANtricity System Manager link:upgrading-drive-firmware-using-santricity-system-manager-online.html[online] or link:upgrading-drive-firmware-using-santricity-system-manager-offline.html[offline] method. 
