---
permalink: sg120-1200/replace-cmos-in-sg120-and-sg1200.html
sidebar: sidebar
keywords: storagegrid, sg120, sg1200, admin node, admin appliance, replacing, replace, CMOS, battery
summary: 'Use this procedure to replace the CMOS coin cell battery on the system board.'
---
= Replace the CMOS batteries in an SG120 or SG1200
:icons: font
:imagesdir: ../media/

[.lead]
Use this procedure to replace the CMOS coin cell batteries on the system board.

.About this task
To prevent service interruptions, confirm that all other Storage Nodes are connected to the grid before starting the CMOS battery replacement or replace the batteries during a scheduled maintenance window when periods of service disruption are acceptable. See the information about https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states[monitoring node connection states^].

.Before you begin

* You have link:verify-component-to-replace.html[verified the SG120 or SG1200 where the CMOS batteries need to be replaced].
* You have obtained the correct replacement CMOS batteries (CR2032).
* You have link:locating-sg120-and-sg1200-in-data-center.html[physically located the SG120 or SG1200 appliance] where you are replacing the CMOS batteries in the data center.
* You have recorded the current BMC configuration of the appliance, if it remains available.
. Log in to the appliance to be replaced:
  .. Enter the following command: `ssh admin@_grid_node_IP_`
  .. Enter the password listed in the `Passwords.txt` file.
  .. Enter the following command to switch to root: `su -`
  .. Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
. Enter: `*run-host-command ipmitool lan print*` to display the current BMC configuration for the appliance.
+
NOTE: A link:power-sg120-and-sg1200-off-on.html#shut-down-the-sg120-or-sg1200-appliance[controlled shutdown of the appliance] is required before removing the appliance from the rack.

* You have disconnected all cables and link:reinstalling-sg120-and-sg1200-cover.html[removed the appliance cover].


include::../_include/2025-replace-cmos.adoc[]