---
permalink: sg120-1200/replacing-fan-in-sg120-and-sg1200.html
sidebar: sidebar
keywords: storagegrid, sg120, sg1200, admin appliance, replacing, replace, fan, remove, removing, removal, install, installing
summary: 'The SG120 or SG1200 appliances have eight cooling fans. If one of the fans fails, you must replace it as soon as possible to ensure that the appliance has proper cooling.'
---
= Replace fan in an SG120 or SG1200
:icons: font
:imagesdir: ../media/

[.lead]
The SG120 or SG1200 appliances have eight cooling fans. If one of the fans fails, you must replace it as soon as possible to ensure that the appliance has proper cooling.

.About this task
To prevent service interruptions, confirm that all other Storage Nodes are connected to the grid before starting the fan replacement or replace the fan during a scheduled maintenance window when periods of service disruption are acceptable. See the information about https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states[monitoring node connection states^].

The appliance node will not be accessible while you replace the fan.

The cooling fans are accessible after you take the top cover off of the appliance.

NOTE: Each of the two power supply units also contain a fan. The power supply fans aren't included in this procedure.

.Before you begin

* You have the correct replacement fan.
* You have link:verify-component-to-replace.html[determined the location of the fan to replace].

* You have link:locating-sg120-and-sg1200-in-data-center.html[physically located the SG120 or SG1200 appliance] where you are replacing the fan in the data center.
+
NOTE: A link:power-sg120-and-sg1200-off-on.html#shut-down-the-sg120-or-sg1200-appliance[controlled shutdown of the appliance] is required before removing the appliance from the rack.

* You have disconnected all cables and link:reinstalling-sg120-and-sg1200-cover.html[removed the appliance cover].

* You have confirmed that the other fans are installed and running.



include::../_include/2025-replace-fan.adoc[]


include::../_include/fru-statement.adoc[] 