settings:
  name: "StorageGRID Appliances"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true
sidebar:
  entries:
    - title: StorageGRID Appliance Docs
      url: "/index.html"
    - title: Quick start for StorageGRID
      url: "/quick-start.html"
    - title: Learn about StorageGRID appliances
      entries:
      - title: SGF6112 storage appliance
        url: "/installconfig/hardware-description-sg6100.html"
      - title: SG6000 storage appliances
        url: "/installconfig/hardware-description-sg6000.html"
      - title: SG5700 storage appliances
        url: "/installconfig/hardware-description-sg5700.html"
      - title: SG100 and SG1000 services appliances
        url: "/installconfig/hardware-description-sg100-and-1000.html"   
    - title: Install appliance hardware
      url: "/landing-appl-install/index.html"
      entries:
      - section: installconfig
    - title: Maintain appliance hardware
      entries:
      - section: commonhardware
      - section: sg6100
      - section: sg6000
      - section: sg5700
      - section: sg5600
      - section: sg100-1000
    - title: StorageGRID software documentation
      url: /storagegrid-documentation.html
    - title: Enable StorageGRID
      url: /storagegrid-enable.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family