---
sidebar: sidebar
permalink: storagegrid-documentation.html
keywords: storagegrid, software, grid
summary: "Learn how to configure and use a StorageGRID system."
---
= StorageGRID software documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Go to https://docs.netapp.com/us-en/storagegrid/index.html[StorageGRID 12.0 Documentation^] to learn how to configure and use a StorageGRID 12.0 system.

The StorageGRID doc site includes information such as:

* Networking guidelines.
* Installation instructions for Linux and VMware nodes.
* StorageGRID upgrade and hotfix instructions.
* Administration instructions for configuring your system, including using information lifecycle management (ILM) to protect object data.
* Instructions for using StorageGRID tenant accounts and the S3 REST API.
* Monitoring and troubleshooting instructions, including information about alerts, audit messages, and system logs.
* Instructions for maintaining a StorageGRID system, which includes adding new StorageGRID volumes, nodes, or site; recovering failed nodes and volumes; decommissioning nodes or sites; and performing other maintenance on your grid.

== Other versions

You can find documentation for other versions of NetApp StorageGRID software here:

* https://docs.netapp.com/us-en/storagegrid-119/index.html[StorageGRID 11.9 documentation^]

* https://docs.netapp.com/us-en/storagegrid-118/index.html[StorageGRID 11.8 documentation^]

* https://docs.netapp.com/us-en/storagegrid-117/index.html[StorageGRID 11.7 documentation^]

* https://docs.netapp.com/us-en/storagegrid-116/index.html[StorageGRID 11.6 documentation^]

* https://docs.netapp.com/us-en/storagegrid-115/index.html[StorageGRID 11.5 documentation^]

* https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61023[StorageGRID 11.4 documentation^]
