---
sidebar: sidebar
permalink: whats-new-appliances.html
keywords: storagegrid, appliance, whats new
summary: "Learn what's new in this doc site."
---
= What's new for appliances
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new for StorageGRID appliances.

== SG5812 and SG5860 appliances
The new StorageGRID SG5812 and SG5860 appliances are integrated storage storage and computing platforms that operate as Storage Nodes in a StorageGRID grid. The appliances can be used in a hybrid grid environment that combines appliance Storage Nodes and virtual (software-based) Storage Nodes. See the https://review.docs.netapp.com/us-en/storagegrid-appliances_quartet-idevine-20231016/installconfig/hardware-description-sg5800.html[SG5800 appliances: Overview] to learn more.

== SG6160 appliance
The StorageGRID new SG6160 appliance includes a compute controller and a storage controller shelf that contains two storage controllers and 60 drives, as well as two NVMe SSD drives for caching. The SSD drives are in a RAID that provides resilient object storage. Optionally, 60-drive expansion shelves can be added to the SG6160. See link:installconfig/hardware-description-sg6100.html[SGF6112 appliance: Overview] to learn more.

