---
sidebar: sidebar
permalink: whats-new-appliances.html
keywords: storagegrid, appliance, whats new
summary: "Learn what's new in this doc site."
---
= What's new in StorageGRID appliances
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in StorageGRID appliances.

== SGF6212 appliance

The new StorageGRID SGF6212 storage appliance features a compact design with compute controller and storage controller integrated into a 1U chassis. The appliance supports 12 SSD NVMe drives in a RAID that provides resilient object storage. See link:installconfig/hardware-description-sg6200.html[SGF6212 appliance: Overview].

== SG6260 appliance
The new StorageGRID SG6260 appliance includes a compute controller and a storage controller shelf that contains two storage controllers and 60 drives, as well as two NVMe SSD drives for caching. Optionally, 60-drive expansion shelves can be added to the SG6260. Refer to link:./installconfig/hardware-description-sg6200.html[SGF6200 appliances: Overview] to learn more.

== Client Network can be configured without an IP address
You can now enable the Client Network without specifying an IP address. This allows the Client Network to have VLAN interfaces configured in StorageGRID without requiring an extra IP address for the interface itself. Refer to link:.//installconfig/setting-ip-configuration.html[Configure StorageGRID IP addresses].

== Version numbers for StorageGRID software and Appliance Installer aligned
With StorgeGRID version 12.0, the version number of the StorageGRID Appliance Installer matches the version of StorageGRID software. Users no longer need to figure out which versions work together. Refer to link:./installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html[Verify and upgrade StorageGRID Appliance Installer version].

== BMC information
Detailed information about using the StorageGRID appliance BMC interface is now available. Refer to link:./commonhardware/use-bmc.html[Use the StorageGRID appliance baseboard management controller (BMC)].




