---
sidebar: sidebar
permalink: whats-new-appliances.html
keywords: storagegrid, appliance, whats new
summary: "Learn what's new in this doc site."
---
= What's new in StorageGRID appliances
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in StorageGRID appliances.

== Client Network can be configured without an IP address
You can now enable the Client Network without specifying an IP address. This allows the Client Network to have VLAN interfaces configured in StorageGRID without requiring an extra IP address for the interface itself. Refer to link:.//installconfig/setting-ip-configuration.html[Configure StorageGRID IP addresses].

== Version numbers for StorageGRID software and Appliance Installer aligned
With StorgeGRID version 12.0, the version number of the StorageGRID Appliance Installer matches the version of StorageGRID software. Users no longer need to figure out which versions work together. Refer to link:./installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html[Verify and upgrade StorageGRID Appliance Installer version].

== BMC information
Detailed information about using the StorageGRID appliance BMC interface is now available. Refer to link:./commonhardware/use-bmc.html[Use the StorageGRID appliance baseboard management controller (BMC)].


== SG120 and SG1200 services appliances
The new StorageGRID SG120 and SG1200 services appliances are an evolutionary hardware update that provide improved administrative and load-balancing performance. Refer to link:./installconfig/hardware-description-sg120-and-1200.html[SG120 and SG1200 services appliance: Overview].

