---
permalink: sg100-1000/replace-cmos-in-sg100-and-sg1000.html
sidebar: sidebar
keywords: storagegrid, sg100, sg1000, admin node, admin appliance, replacing, replace, CMOS, battery
summary: 'Use this procedure to replace the CMOS coin cell battery on the system board.'
---
= Replace the CMOS battery in an SG100 or SG1000
:icons: font
:imagesdir: ../media/

[.lead]
Use this procedure to replace the CMOS coin cell battery on the system board.

Use these procedures to: 

* Remove the CMOS battery
* Reinstall the CMOS battery

== Remove the CMOS battery

.Before you begin

* You have link:verify-component-to-replace-sg100-and-sg1000.html[verified the SG100 or SG1000 where the CMOS battery needs to be replaced].
* You have link:locating-controller-in-data-center.html[physically located the SG100 or SG1000 appliance] where you are replacing the CMOS battery in the data center.
+
NOTE: A link:shut-down-sg100-and-sg1000.html[controlled shutdown of the appliance] is required before removing the appliance from the rack.

* You have disconnected all cables and link:reinstalling-sg100-and-sg1000-controller-cover.html[removed the appliance cover].

.About this task
To prevent service interruptions, confirm that all other Storage Nodes are connected to the grid before starting the CMOS battery replacement or replace the battery during a scheduled maintenance window when periods of service disruption are acceptable. See the information about https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states[monitoring node connection states^].

include::../_include/2024-replace-cmos-l.adoc[]
