---
permalink: sg6200/replace-cmos-in-sg6200.html
sidebar: sidebar
keywords: storagegrid, sg6200, SGF6212, storage node, storage appliance, Replacing, replace, CMOS, battery, sg6260
summary: 'Use this procedure to replace the CMOS coin cell battery on the system board.'
---
= Replace SGF6212 or SG6200-CN CMOS battery
:icons: font
:imagesdir: ../media/

[.lead]
Use this procedure to replace the CMOS coin cell battery on the system board.

.About this task
To prevent service interruptions, confirm that all other Storage Nodes are connected to the grid before starting the CMOS battery replacement or replace the battery during a scheduled maintenance window when periods of service disruption are acceptable. See the information about https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states[monitoring node connection states^].

CAUTION: If you have ever used an ILM rule that creates only one copy of an object, you must replace the battery during a scheduled maintenance window because you might temporarily lose access to those objects during this procedure. See information about https://docs.netapp.com/us-en/storagegrid/ilm/why-you-should-not-use-single-copy-replication.html[why you should not use single-copy replication^].

.Before you begin

* You have link:verify-component-to-replace.html[verified the appliance where the CMOS battery needs to be replaced].
* You have link:locating-sg6200-in-data-center.html[physically located the SGF6212 appliance or SG6200-CN controller] where you are replacing the CMOS battery in the data center.
* You have recorded the current BMC configuration of the appliance, if it remains available.
. Log in to the appliance to be replaced:
  .. Enter the following command: `ssh admin@_grid_node_IP_`
  .. Enter the password listed in the `Passwords.txt` file.
  .. Enter the following command to switch to root: `su -`
  .. Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
. Enter: `*run-host-command ipmitool lan print*` to display the current BMC configuration for the appliance.
+
NOTE: A link:power-sg6200-off-on.html#shut-down-the-sgf6212-appliance-or-sg6200-cn-controller[controlled shutdown of the appliance] is required before removing the appliance from the rack.

* You have disconnected all cables and link:reinstalling-sg6200-cover.html[removed the appliance cover].

include::../_include/2025-replace-cmos.adoc[]
