---
permalink: installconfig/configuring-hardware.html
sidebar: sidebar
keywords: storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking
summary: 'After applying power to the appliance, you configure the network connections that will be used by StorageGRID. '
---
= Set up StorageGRID appliance hardware
:icons: font
:imagesdir: ../media/

[.lead]
After applying power to the appliance, you configure the network connections that will be used by StorageGRID. 

== Required hardware configurations

=== Network connections

You must configure and verify the required network connections for all appliances:

* link:../installconfig/accessing-storagegrid-appliance-installer.html[Access the Appliance Installer]
* link:../installconfig/configuring-network-links.html[Configure network links]
* link:../installconfig/verifying-port-level-network-connections.html[Verify port-level network connections]

=== BMC interface

You must link:../installconfig/configuring-bmc-interface.html[configure the baseboard management controller (BMC) interface] if you are installing one of the following appliances:

* SG100
* SG110
* SG120
* SG1000
* SG1100
* SG1200
* SGF6024
* SGF6112
* SGF6212
* SG6060
* SG6160
* SG6260

You can use the BMC interface to configure SNMP and other low-level settings for your appliances. It also enables you to troubleshoot your hardware installation, determine your appliance's power state, and control the identify LED on your appliance.

To learn more about what features you can use with the BMC, refer to link:../commonhardware/use-bmc.html[Use the BMC interface].


== Optional hardware configurations

=== SANtricity System Manager

You can link:../installconfig/accessing-and-configuring-santricity-system-manager.html[configure SANtricity System Manager] if you have one of the following appliances:

* SG5712
* SG5760
* SG5812
* SG5860
* SGF6024
* SG6060
* SG6160
* SG6260

SANtricity System Manager software allows you to:

* Monitor system performance data, hardware component status, and support functions for your appliance
* Manage drive security keys, SNMP and syslofg alerts, and administrator passwords for accessing SANtricity System Manager
* Configure access to E-Series AutoSupport

=== Enable node or drive encryption

You can link:../installconfig/optional-enabling-node-encryption.html[enable node or drive encryption] to protect the drives and disks in your appliance.

=== Change RAID mode

You can link:../installconfig/optional-changing-raid-mode.html[change the RAID mode of your storage appliance] to accommodate your storage and recovery needs.

The following appliances support changing the RAID mode:

* SG5760
* SG5860
* SGF6024
* SG6060
* SG6160
* SG6260

=== Remap network ports

You can link:../installconfig/optional-remapping-network-ports-for-appliance.html[remap the network ports on your appliance] to optimize your network connections.
