---
permalink: installconfig/configuring-hardware.html
sidebar: sidebar
keywords: storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking
summary: 'After applying power to the appliance, you configure the network connections that will be used by StorageGRID. '
---
= Set up hardware overview
:icons: font
:imagesdir: ../media/

[.lead]
After applying power to the appliance, you configure the network connections that will be used by StorageGRID. 

== Required hardware configurations

=== Network connections

You must configure and verify the required network connections for all appliances:

* link:../installconfig/accessing-storagegrid-appliance-installer.html[Access the Appliance Installer]
* link:../installconfig/configuring-network-links.html[Configure network links]
* link:../installconfig/verifying-port-level-network-connections.html[Verify port-level network connections]

You also link:../installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html[verify and upgrade the StorageGRID Appliance Installer version], link:../installconfig/verifying-network-connections.html[verify the network connections for your appliance], and link:../installconfig/setting-ip-configuration.html[set the IP configuration for your appliance].

=== SANtricity System Manager

You must configure SANtricity System Manager if you have one of the following appliances:

* SG5712
* SG5760
* SG5812
* SG5860
* SG6000
* SG6160

SANtricity System Manager software allows you to monitor and manage the health of your storage controllers and disks and configure access to E-Series AutoSupport.

=== BMC interface 

You must configure the baseboard management controller (BMC) interface if you have one of the following appliances:

* SG100
* SG110
* SG1000
* SG1100
* SG6000
* SGF6112
* SG6160

You can use the BMC interface to configure SNMP and other low-level settings for your appliances. It also enables you to troubleshoot your hardware installation, determine your appliance's power state, and control the identify LED on your appliance.

To use the BMC with a supported StorageGRID appliance, link:../installconfig/configuring-bmc-interface.html[configure the network settings for the BMC interface]. To learn more about what features you can use with the BMC, refer to link:../commonhardware/use-bmc.html[Use the BMC interface].


== Optional hardware configurations

=== Enable node or drive encryption

You can link:../installconfig/optional-enabling-node-encryption.html[enable node or drive encryption] to protect the drives and disks in your appliance.

=== Change RAID mode

You can link:../installconfig/optional-changing-raid-mode.html[change the RAID mode of your storage appliance] to accommodate your storage and recovery needs.

The following appliances support changing the RAID mode:

* SG5760
* SG5860
* SG6000
* SG6160

=== Remap network ports

You can link:../installconfig/optional-remapping-network-ports-for-appliance.html[remap the network ports on your appliance] to optimize your network connections.

