---
permalink: installconfig/configuring-snmp-settings-for-bmc.html
sidebar: sidebar
keywords: SNMP, configure, setup, set up 
summary: 'If you are familiar with configuring SNMP for hardware, you can use the BMC interface to configure the SNMP settings for the SG6100, SG6000, and services appliances. You can provide secure community strings, enable SNMP Trap, and specify up to five SNMP destinations.'
---
= Configure SNMP settings for BMC
:icons: font
:imagesdir: ../media/

[.lead]
If you are familiar with configuring SNMP for hardware, you can use the BMC interface to configure the SNMP settings for the SG6100, SG6000, and services appliances. You can provide secure community strings, enable SNMP Trap, and specify up to five SNMP destinations.

.Before you begin

* You know how to access the BMC dashboard.
* You have experience in configuring SNMP settings for SNMPv1-v2c equipment.

NOTE: BMC settings made by this procedure might not be preserved if the appliance fails and has to be replaced.  Make sure you have a record of all settings you have applied, so they can be easily reapplied after a hardware replacement if necessary.

These instructions show the latest version of BMC firmware available for some StorageGRID appliances. Your StorageGRID appliance might have a BMC firmware version that is slightly different. 

*	The BMC firmware updates during StorageGRID software upgrades. If you are not running the latest version of StorageGRID software, you can update your appliance to the latest StorageGRID version to install the https://review.docs.netapp.com/us-en/storagegrid-119_main/upgrade/how-your-system-is-affected-during-upgrade.html#appliance-firmware-is-upgraded[latest BMC firmware version available for your appliance].
*	If your BMC appears different before or after a StorageGRID update: 
** See https://docs.netapp.com/us-en/storagegrid-117/installconfig/configuring-snmp-settings-for-bmc.html[Configure SNMP settings for alternate BMC firmware versions].
** link:/commonhardware/use-bmc.html[Use the StorageGRID BMC] might also have information to help you adapt these instructions for your BMC version.

.Steps

. Configure SNMP traps as one or more LAN destinations.
.. From the BMC dashboard, select *Settings* > *Platform Event Filters* > *LAN Destinations*.
.. For Destination Type, select *SNMP Trap*.
.. For SNMP Destination Address, enter the target IP address.
+
NOTE: Use an IP address for the SNMP Destination Address. DNS names aren't supported.
.. Select *Save*.
. If you are using SNMP traps to deliver alert notifications, see the Platform Event Filters section of the *ADD-LINK-TO-KB-WITH-QUANTA-PDF - link text [BMC User Guide]* for information about using the BMC to configure Alert Policies and Event Filters.
