---
permalink: installconfig/configuring-snmp-settings-for-bmc.html
sidebar: sidebar
keywords: SNMP, configure, setup, set up 
summary: 'If you are familiar with configuring SNMP for hardware, you can use the BMC interface to configure the SNMP settings for the SG6100, SG6000, and services appliances. You can provide secure community strings, enable SNMP Trap, and specify up to five SNMP destinations.'
---
= Configure SNMP settings for BMC
:icons: font
:imagesdir: ../media/

[.lead]
If you are familiar with configuring SNMP for hardware, you can use the BMC interface to configure the SNMP settings for the SG6100, SG6000, and services appliances. You can provide secure community strings, enable SNMP Trap, and specify up to five SNMP destinations.

.Before you begin

* You know how to access the BMC dashboard.
* You have experience in configuring SNMP settings for SNMPv1-v2c equipment.

NOTE: BMC settings made by this procedure might not be preserved if the appliance fails and has to be replaced.  Make sure you have a record of all settings you have applied, so they can be easily reapplied after a hardware replacement if necessary.

.Steps

. Configure SNMP traps as one or more LAN destinations.
.. From the BMC dashboard, select *Settings* > *Platform Event Filters* > *LAN Destinations*.
.. For Destination Type, select *SNMP Trap*.
.. For SNMP Destination Address, enter the target IP address.
+
NOTE: Use an IP address for the SNMP Destination Address. DNS names aren't supported.
.. Select *Save*.
. If you are using SNMP traps to deliver alert notifications, see the Platform Event Filters section of the *ADD-LINK-TO-KB-WITH-QUANTA-PDF - link text [BMC User Guide]* for information about using the BMC to configure Alert Policies and Event Filters.
