---
permalink: installconfig/connecting-power-cords-and-applying-power.html
sidebar: sidebar
keywords: storagegrid, wire, wiring, cabling, cable, Connecting, connect, power cords, power, applying power, apply power, turn on, power up, ac, ac power 
summary: 'After connecting the network cables, you are ready to apply power to the appliance.'
---
= Connect power cords and apply power
:icons: font
:imagesdir: ../media/

[.lead]
After connecting the network cables, you are ready to apply power to an appliance, controller, or expansion shelf.

[role="tabbed-block"]
====

.SGF6112
--

.Steps

. Connect a power cord to each of the two power supply units in the appliance.
. Connect these two power cords to two different power distribution units (PDUs) in the cabinet or rack.
. If the power button on the front of the appliance is not currently illuminated blue, press the button to turn on power to the appliance.
+
Don't press the power button again during the power-on process.
+
The LED on the power supply should be illuminated green without blinking. 

. If errors occur, correct any issues.
. Attach the front bezel to the appliance if removed.

--

.SG6000
--

.Steps

. Confirm that both controllers in the storage controller shelf are off.
+
CAUTION: *Risk of electrical shock* -- Before connecting the power cords, make sure that the power switches for each of the two storage controllers are off.

. If you have expansion shelves, confirm that both of the IOM power switches are off.
+
CAUTION: *Risk of electrical shock* -- Before connecting the power cords, make sure that the two power switches for each of the expansion shelves are off.

. Connect a power cord to each of the two power supply units in the SG6000-CN controller.
. Connect these two power cords to two different power distribution units (PDUs) in the cabinet or rack.
. Connect a power cord to each of the two power supply units in the storage controller shelf.
. If you have expansion shelves, connect a power cord to each of the two power supply units in each expansion shelf.
. Connect the two power cords in each storage shelf (including the optional expansion shelves) to two different PDUs in the cabinet or rack.
. If the power button on the front of the SG6000-CN controller is not currently illuminated blue, press the button to turn on power to the controller.
+
Don't press the power button again during the power-on process.

. Turn on the two power switches on the back of the storage controller shelf. If you have expansion shelves, turn on the two power switches for each shelf.
 ** Don't turn off the power switches during the power-on process.
 ** The fans in the storage controller shelf and optional expansion shelves might be very loud when they first start up. The loud noise during start-up is normal.
. After the components have booted up, check their status.
 ** Check the seven-segment display on the back of each storage controller. Refer to the article about viewing boot-up status codes for more information.
 ** Verify that the power button on the front of the SG6000-CN controller is lit.
. If errors occur, correct any issues.
. Attach the front bezel to the SG6000-CN controller if removed.

--

.SG5700
--

.Before you begin

Both appliance power switches must be off before connecting power.

CAUTION: *Risk of electrical shock* -- Before connecting the power cords, make sure that the two power switches on the appliance are off.

.Steps

. Confirm that the two power switches on the appliance are off.
. Connect the two power cords to the appliance.
. Connect the two power cords to different power distribution units (PDUs) in the cabinet or rack.
. Turn on the two power switches on the appliance.
 ** Don't turn off the power switches during the power-on process.
 ** The fans are very loud when they first start up. The loud noise during start-up is normal.
. After the controllers have booted up, check their seven-segment displays.

--

.SG110 and SG1100
--

.Steps

. Connect a power cord to each of the two power supply units in the appliance.
. Connect these two power cords to two different power distribution units (PDUs) in the cabinet or rack.
. If the power button on the front of the appliance is not currently illuminated blue, press the button to turn on power to the appliance.
+
Don't press the power button again during the power-on process.
+
The LED on the power supply should be illuminated green without blinking. 

. If errors occur, correct any issues.
. Attach the front bezel to the appliance if removed.

--

.SG100 and SG1000
--

.Steps

. Connect a power cord to each of the two power supply units in the appliance.
. Connect these two power cords to two different power distribution units (PDUs) in the cabinet or rack.
. If the power button on the front of the appliance is not currently illuminated blue, press the button to turn on power to the appliance.
+
Don't press the power button again during the power-on process.

. If errors occur, correct any issues.
. Attach the front bezel to the appliance if removed.

--
====

.Related information

link:viewing-status-indicators.html[View status indicators]