---
permalink: installconfig/optional-changing-raid-mode.html
sidebar: sidebar
keywords: storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, RAID 6
summary: 'On some appliance models, you can change to a different RAID mode on the appliance to accommodate your storage and recovery requirements. You can only change the mode before deploying the appliance Storage Node.'
---
= Optional: Change RAID mode (SG5760, SG5860, SG6000, and SG6160)
:icons: font
:imagesdir: ../media/

[.lead]
On some appliance models, you can change to a different RAID mode on the appliance to accommodate your storage and recovery requirements. You can only change the mode before deploying the appliance Storage Node.

If you are using ConfigBuilder to generate a JSON file, you can change the RAID mode automatically. See link:automating-appliance-installation-and-configuration.html[Automate appliance installation and configuration].

.About this task

If supported by your appliance, you can choose one of the following volume configuration options:

NOTE: Volume sizes are not consistent across all DDP and RAID types. Variations in how DDP and RAID6 operate cause different volume sizes.

* *Dynamic Disk Pools (DDP)*: This mode uses two parity drives for every eight data drives. This is the default and recommended mode for all appliances. 

** When compared to RAID 6, DDP delivers better system performance, reduced rebuild times after drive failures, and ease of management. 
** DDP creates all the required logical unit numbers (LUNs) in one group.
** DDP provides drawer-loss protection in SG5760, SG5860, and SG6160 appliances.
+
NOTE: DDP does not provide drawer loss protection in SG6060 appliances because of the two SSDs. Drawer loss protection is effective in any expansion shelves that are added to an SG6060. 

* *DDP16*: This mode uses two parity drives for every 16 data drives, which results in higher storage efficiency compared to DDP. 

** Compared to RAID 6, DDP16 delivers better system performance, reduced rebuild times after drive failures, ease of management, and comparable storage efficiency. 
** To use DDP16 mode, your configuration must contain at least 20 drives. 
** DDP16 create all the required LUNs in one group.
** DDP16 does not provide drawer loss protection. 

* *RAID6*: This mode uses two parity drives for every 16 or more data drives. It is a hardware protection scheme that uses parity stripes on each disk, and allows for two disk failures within the RAID set before any data is lost. To use RAID 6 mode, your configuration must contain at least 20 drives. Although RAID 6 can increase storage efficiency of the appliance when compared to DDP, it is not recommended for most StorageGRID environments.

** RAID 6 provides one global hot spare per expansion shelf. For example, an SG6160 with two expansion shelves has three hot spares.
** The maximum RAID 6 size is 19+2 on an SG6160 or 21+2 on an SGF6024.
** StorageGRID attempts to create at least two RAID 6 groups. On a 60-drive storage appliance, StorageGRID creates three volume groups, each with a minimum of 18 drives (16+2). In practice, an SG6160 has three volume groups with RAID sizes of 19+2, 17+2, and 17+2 plus one hot spare.
** On an SG6160, RAID 6 spreads the LUNs across multiple volume groups.
** RAID 6 volumes are slightly larger, allowing node cloning from DDP16 in many cases. Volume sizes can vary between volume groups in a RAID 6 configuration.

CAUTION: If any volumes have already been configured or if StorageGRID was previously installed, changing the RAID mode causes the volumes to be removed and replaced. Any data on those volumes will be lost.

[role="tabbed-block"]
====

.SG5760
--
.Before you begin

* You have an SG5760 with 60 drives. If you have an SG5712, you must use the default DDP mode.
* You are using any client that can connect to StorageGRID.
* The client has a https://docs.netapp.com/us-en/storagegrid-118/admin/web-browser-requirements.html[supported web browser^].

.Steps

. Using the service laptop, open a web browser and access the StorageGRID Appliance Installer: +
`*https://_E5700SG_Controller_IP_:8443*`
+
Where `_E5700SG_Controller_IP_` is any of the IP addresses for the E5700SG controller.

. Select *Advanced* > *RAID Mode*.
. On the *Configure RAID Mode* page, select the desired RAID mode from the Mode drop-down list.
. Click *Save*.
--


.SG5860
--
.Before you begin

* You have an SG5860 with 60 drives. If you have an SG5812, you must use the default DDP mode.
* You are using any client that can connect to StorageGRID.
* The client has a https://docs.netapp.com/us-en/storagegrid-118/admin/web-browser-requirements.html[supported web browser^].

.Steps

. Using the service laptop, open a web browser and access the StorageGRID Appliance Installer: +
`*https://_SG5800_Controller_IP_:8443*`
+
Where `_SG5800_Controller_IP_` is any of the IP addresses for the SG5800 controller.

. Select *Advanced* > *RAID Mode*.
. On the *Configure RAID Mode* page, select the desired RAID mode from the Mode drop-down list.
. Click *Save*.
--

.SG6000
--
.Before you begin

* You are using any client that can connect to StorageGRID.
* The client has a  https://docs.netapp.com/us-en/storagegrid-118/admin/web-browser-requirements.html[supported web browser^].

.Steps

. Open a browser, and enter one of the IP addresses for the appliance's compute controller.
+
`*https://_Controller_IP_:8443*`
+
`_Controller_IP_` is the IP address of the compute controller (not the storage controller) on any of the three StorageGRID networks.
+
The StorageGRID Appliance Installer Home page appears.

. Select *Advanced* > *RAID Mode*.
. On the *Configure RAID Mode* page, select the desired RAID mode from the Mode drop-down list.
. Click *Save*.
--

.SG6160
--
.Before you begin

* You are using any client that can connect to StorageGRID.
* The client has a  https://docs.netapp.com/us-en/storagegrid-118/admin/web-browser-requirements.html[supported web browser^].

.Steps

. Open a browser, and enter one of the IP addresses for the appliance's compute controller.
+
`*https://_Controller_IP_:8443*`
+
`_Controller_IP_` is the IP address of the compute controller (not the storage controller) on any of the three StorageGRID networks.
+
The StorageGRID Appliance Installer Home page appears.

. Select *Advanced* > *RAID Mode*.
. On the *Configure RAID Mode* page, select the desired RAID mode from the Mode drop-down list.
. Click *Save*.
--

====
