---
permalink: installconfig/reviewing-appliance-network-connections.html
sidebar: sidebar
keywords: network connections, appliance, grid, admin, client, bmc, management
summary: 'Before installing the StorageGRID appliance, you should understand which networks can be connected to the appliance.'
---
= StorageGRID network types
:icons: font
:imagesdir: ../media/

[.lead]
Before installing the StorageGRID appliance, you should understand which networks can be connected to the appliance and how the ports on each controller are used. StorageGRID network requirements are fully explained in the https://review.docs.netapp.com/us-en/storagegrid-118_main/network/index.html[Networking guidelines^].

Refer to the instructions for your appliance to determine what information you need:

* link:gathering-installation-information-sg6100.html[SGF6112]
* link:gathering-installation-information-sg6000.html[SG6000]
* link:gathering-installation-information-sg5700.html[SG5700]
* link:gathering-installation-information-sg100-and-sg1000.html[SG100 and SG1000]

Alternatively, you can work with your NetApp Professional Services consultant to use the NetApp ConfigBuilder tool to streamline and automate the configuration steps. See link:automating-appliance-installation-and-configuration.html[Automate appliance installation and configuration].

When you deploy a StorageGRID appliance as a node in a StorageGRID system, you can connect it to the following networks:

* *Grid Network for StorageGRID*: The Grid Network is used for all internal StorageGRID traffic. It provides connectivity between all nodes in the grid, across all sites and subnets. The Grid Network is required.

* *Admin Network for StorageGRID*: The Admin Network is a closed network used for system administration and maintenance. The Admin Network is typically a private network and does not need to be routable between sites. The Admin Network is optional.
* *Client Network for StorageGRID:* The Client Network is an open network used to provide access to client applications, including S3 and Swift. The Client Network provides client protocol access to the grid, so the Grid Network can be isolated and secured. You can configure the Client Network so that the appliance can be accessed over this network using only the ports you choose to open. The Client Network is optional.

* *Management network for SANtricity* (optional for storage appliances, not needed for the SGF6112): This network provides access to SANtricity System Manager, allowing you to monitor and manage the hardware components in the appliance and storage controller shelf. This management network can be the same as the Admin Network for StorageGRID, or it can be an independent management network.

* *BMC management network* (optional for SG100, SG1000, SG6000, and SGF6112): This network provides access to the baseboard management controller in the SG100, SG1000, SG6000, and SGF6112 appliances allowing you to monitor and manage the hardware components in the appliance. This management network can be the same as the Admin Network for StorageGRID, or it can be an independent management network.
+
If the optional BMC management network is not connected, some support and maintenance procedures will be more difficult to perform. You can leave the BMC management network unconnected except when needed for support purposes.

NOTE: For detailed information about StorageGRID networks, see the https://review.docs.netapp.com/us-en/storagegrid-118_main/network/storagegrid-network-types.html[StorageGRID network types^].
