---
permalink: installconfig/setting-up-email-notifications-for-alerts.html
sidebar: sidebar
keywords: email, notifications, alerts, set up, setup, configure, configuration, bmc 
summary: 'If you want email notifications to be sent when alerts occur, use the BMC interface to configure SMTP settings, users, LAN destinations, alert policies, and event filters.'
---
= Set up email notifications for BMC alerts
:icons: font
:imagesdir: ../media/

[.lead]
If you want email notifications to be sent when alerts occur, use the BMC interface to configure SMTP settings, users, LAN destinations, alert policies, and event filters.

NOTE: BMC settings made by this procedure might not be preserved if a controller or appliance fails and has to be replaced. Make sure you have a record of all settings you have applied, so they can be easily reapplied after a hardware replacement if necessary.

.Before you begin

You know how to access the BMC dashboard.

.About this task

In the BMC interface, use the *User Management* and *Platform Event Filters* options on the Settings page to configure email notifications.

These instructions show the latest version of BMC firmware available for some StorageGRID appliances. Your StorageGRID appliance might have a BMC firmware version that is slightly different. 

* The BMC firmware updates during StorageGRID software upgrades. If you are not running the latest version of StorageGRID software, you can update your appliance to the latest StorageGRID version to install the https://review.docs.netapp.com/us-en/storagegrid-119_main/upgrade/how-your-system-is-affected-during-upgrade.html#appliance-firmware-is-upgraded[latest BMC firmware version available for your appliance].
* If your BMC appears different before or after a StorageGRID update: 
** See https://docs.netapp.com/us-en/storagegrid-117/installconfig/setting-up-email-notifications-for-alerts.html[Set up email notifications for BMC alerts for alternate BMC firmware versions].
** link:../commonhardware/use-bmc.html[Use the StorageGRID BMC] might also have information to help you adapt these instructions for your BMC version.

.Steps

. Configure email notifications as one or more LAN destinations.
.. From the BMC dashboard, select *Settings* > *Platform Event Filters* > *LAN Destinations*.
.. For Destination Type, select *E-Mail*.
.. Select a BMC Username to receive the email alert from the list of BMC users. Alert email will be sent to the email address configured for this user.
NOTE: To configure BMC users, select *Settings* > *User Management*. See the User Management section of the https://kb.netapp.com/hybrid/StorageGRID/Platforms/How_to_use_StorageGRID_Appliance_BMC_with_vendor_supplied_user_guide[BMC User Guide] for more information.
.. Enter an EMail Subject and Email Message for the email alert.
+
NOTE: An EMail Subject and Email Message are not used for AMI-Format email users.
.. Select *Save*.
. See the Platform Event Filters section of the https://kb.netapp.com/hybrid/StorageGRID/Platforms/How_to_use_StorageGRID_Appliance_BMC_with_vendor_supplied_user_guide[BMC User Guide] for information about using the BMC to configure Alert Policies and Event Filters.
