// Replace cover SGF6212, SG120, SG1200
// Intro, before you begin, and after you finish are in referencing topic
== Remove cover

.Steps

. Wrap the strap end of an ESD wristband around your wrist and secure the clip end to a metal ground to prevent static discharge when working inside the appliance.
. link:reinstalling-sg120-and-sg1200-into-cabinet-or-rack.html[Remove the appliance from the cabinet or rack] to access the top cover.
. Unlock the cover latch by pressing the blue lock button on the appliance cover.
. Rotate the latch up and back toward the rear of the appliance chassis until it stops; then, carefully lift the cover from the chassis and set it aside.


== Reinstall cover

.Steps

. With the cover latch open, align the cover above the chassis and carefully lower it.

. Rotate the cover latch forward and down until it stops and the cover fully seats into the chassis. Verify that there are no gaps along the front edge of the cover.
+
If the cover is not fully seated, you might not be able to slide the appliance into the rack.

. Optional: Turn the blue plastic latch lock one-quarter turn in the lock direction, as shown on the latch lock, to lock it.

