// Replace NIC SG6200-CN, SGF6212, SG120, SG1200
// Intro, before you begin, and about this task are in referencing topic

== Step 1: Remove the NIC

[role="tabbed-block"]
====
.NIC 1/NIC 2
--

.Steps

. Wrap the strap end of the ESD wristband around your wrist, and secure the clip end to a metal ground to prevent static discharge.
. Locate the riser assembly that contains the NIC at the rear of the appliance.
. Rotate the blue locking latch on the riser with the failed NIC up and open.
+
image:../media/drw_s2025_IO_1_2_replace_ieops-2555.svg[Removing NIC 1 or NIC 2 from the riser assembly]

. Carefully lift the riser assembly with the failed NIC upwards using the blue-marked holes. Move the riser assembly toward the front of the chassis as you lift it to allow the external connectors in its installed NIC to clear the chassis.

. Place the riser on a flat anti-static surface with the metal frame side down to access the NIC.

. Open the blue latch on the failed NIC and carefully remove it from the riser assembly. Rock the NIC slightly to help remove the NIC from its connector. Don't use excessive force.
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg[Removing an IO card from the riser assembly]

. Place the riser and NIC on a flat anti-static surface.

--

.NIC 3
--

.Steps

. Wrap the strap end of the ESD wristband around your wrist, and secure the clip end to a metal ground to prevent static discharge.

. Rotate the blue lock on the riser with the failed NIC to the open position.
+
image:../media/drw_s2025_IO_3_replace_ieops-2556.svg[Removing NIC 3 from the riser assembly]

. Carefully lift the riser assembly upwards using the blue-marked hole and riser edge. Move the riser assembly toward the front of the chassis as you lift it to allow the external connectors in its installed NIC to clear the chassis.

. Place the riser on a flat anti-static surface with the metal frame side down to access the NIC.

. Open the blue latch on the failed NIC and carefully remove it from the riser assembly. Rock the NIC slightly to help remove the NIC from its connector. Don't use excessive force.
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg[Removing an IO card from the riser assembly]

. Place the riser and NIC on a flat anti-static surface.
--
====


== Step 2: Reinstall the internal NIC
Install the replacement NIC into the same location as the one that was removed.

[role="tabbed-block"]
====
.NIC 1/NIC 2
--

.Steps

. Wrap the strap end of the ESD wristband around your wrist, and secure the clip end to a metal ground to prevent static discharge.
. Remove the replacement NIC from its packaging.
. Install the replacement NIC into the riser assembly.
.. Ensure the blue latch is in the open position.
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg[Installing an IO card into the riser assembly]
.. Align the NIC with its connector on the riser assembly. Carefully press the NIC into the connector until it is fully seated, and then close the blue latch.

. Reinstall the riser assembly into chassis.
.. Locate the alignment hole on the riser assembly that aligns with a guide pin on the system board to ensure correct riser assembly positioning.
+
image:../media/drw_s2025_io_1_2_reinstall_ieops-2685.svg[Replacing NIC 1 or NIC 2 in the riser assembly]

.. Position the riser assembly in the chassis, making sure that it aligns with the connector on the system board and guide pin. 

.. Carefully press the riser assembly in place along its center line, next to the blue-marked holes, until it is fully seated.

. If you have no other maintenance procedures to perform in the appliance, reinstall the appliance cover, return the appliance to the rack, attach cables, and apply power.

include::../_include/fru-statement.adoc[] 

--

.NIC 3
--

.Steps

. Wrap the strap end of the ESD wristband around your wrist, and secure the clip end to a metal ground to prevent static discharge.
. Remove the replacement NIC from its packaging.
. Install the replacement NIC into the riser assembly.
.. Ensure the blue latch is in the open position.
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg[Installing an IO card into the riser assembly]

.. Align the NIC with its connector on the riser assembly. Carefully press the NIC into the connector until it is fully seated, and then close the blue latch.

. Reinstall the riser assembly into chassis.
.. Position the riser assembly in the chassis, making sure that the edges of the riser assembly correctly align with the edges of the chassis.
+
image:../media/drw_s2025_io_3_replace_ieops-2686.svg[Replacing NIC 3 in the riser assembly]

.. Carefully press the riser assembly in place along its center line, next to the blue-marked hole, until it is fully seated.
.. Rotate the blue lock on the riser to the closed position.

. Remove the protective caps from the NIC ports where you will be reinstalling cables.


. If you have no other maintenance procedures to perform in the appliance, reinstall the appliance cover, return the appliance to the rack, attach cables, and apply power.

include::../_include/fru-statement.adoc[]

--
====



