---
permalink: sg110-1100/replace-cmos-in-sg110-and-sg1100.html
sidebar: sidebar
keywords: storagegrid, sg110, sg1100, admin node, admin appliance, replacing, replace, CMOS, battery
summary: 'Use this procedure to replace the CMOS coin cell battery on the system board.'
---
= Replace the CMOS battery in an SG110 or SG1100
:icons: font
:imagesdir: ../media/

[.lead]
Use this procedure to replace the CMOS coin cell battery on the system board.

Use these procedures to: 

* Remove the CMOS battery
* Reinstall the CMOS battery

== Remove the CMOS battery

.Before you begin

* You have link:verify-component-to-replace.html[verified the SG110 or SG1100 where the CMOS battery needs to be replaced].
* You have link:locating-sg110-and-sg1100-in-data-center.html[physically located the SG110 or SG1100 appliance] where you are replacing the CMOS battery in the data center.
+
NOTE: A link:power-sg110-and-sg1100-off-on.html#shut-down-the-sg110-or-sg1100-appliance[controlled shutdown of the appliance] is required before removing the appliance from the rack.

* You have disconnected all cables and link:reinstalling-sg110-and-sg1100-cover.html[removed the appliance cover].

.About this task
To prevent service interruptions, confirm that all other Storage Nodes are connected to the grid before starting the CMOS battery replacement or replace the battery during a scheduled maintenance window when periods of service disruption are acceptable. See the information about https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states[monitoring node connection states^].

include::../_include/2023-replace-cmos.adoc[]

// 2024 JUL 4, SGRIDDOC-74