---
permalink: sg6100/replace-nic-in-sgf6112.html
sidebar: sidebar
keywords: storagegrid, sg6100, storage node, storage appliance, Replacing, replace, NIC, network interface card
summary: 'You might need to replace a Network Interface Card \(NIC\) in the SGF6112 if it is not functioning optimally or if it has failed.'
---
= Replace internal NIC in the SGF6112 or SG6100-CN
:icons: font
:imagesdir: ../media/

[.lead]
You might need to replace an internal Network Interface Card (NIC) in the SGF6112 or SG6100-CN if it is not functioning optimally or if it has failed.

Use these procedures to: 

* Remove the NIC
* Reinstall the NIC

== Remove the internal NIC

.Before you begin

* You have the correct replacement NIC.
* You have determined the link:verify-component-to-replace.html[location of the NIC to replace].

* You have link:locating-sgf6112-in-data-center.html[physically located the SGF6112 appliance or SG6100-CN controller] where you are replacing the NIC in the data center.
+
NOTE: A link:power-sgf6112-off-on.html#shut-down-the-sgf6112-appliance-or-sg6100-cn-controller[controlled shutdown of the appliance] is required before removing the appliance from the rack.

* You have disconnected all cables and link:reinstalling-sgf6112-cover.html[removed the appliance cover].

.About this task
To prevent service interruptions, confirm that all other Storage Nodes are connected to the grid before starting the Network Interface Card (NIC) replacement or replace the NIC during a scheduled maintenance window when periods of service disruption are acceptable. See the information about https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states[monitoring node connection states^].

CAUTION: If you have ever used an ILM rule that creates only one copy of an object, you must replace the NIC during a scheduled maintenance window because you might temporarily lose access to those objects during this procedure. See information about https://docs.netapp.com/us-en/storagegrid/ilm/why-you-should-not-use-single-copy-replication.html[why you should not use single-copy replication^].

include::../_include/2023-replace-nic.adoc[]