---
permalink: sg6100/replacing-sg6100-cn-controller.html
sidebar: sidebar
keywords: storagegrid, sg6100, storage node, storage appliance, Replacing, replace, sg6100-cn, controller, remove, removing, removal, install, installing, installation
summary: 'You might need to replace the SG6100-CN controller if it is not functioning optimally or if it has failed.'
---
= Replace SG6100-CN controller
:icons: font
:imagesdir: ../media/

[.lead]
You might need to replace the SG6100-CN controller if it is not functioning optimally or if it has failed.

.Before you begin

* You have a replacement controller with the same part number as the controller you are replacing.
* You have labels to identify each cable that is connected to the controller.
* You have physically located the controller to replace in the data center.
+
link:locating-sgf6112-in-data-center.html[Locate controller in data center]

.About this task

The appliance Storage Node will not be accessible when you replace the SG6100-CN controller. If the SG6100-CN controller is functioning sufficiently, you can perform a controlled shutdown at the start of this procedure.

NOTE: If you are replacing the controller before installing StorageGRID software, you might not be able to access the StorageGRID Appliance Installer immediately after completing this procedure. While you can access the StorageGRID Appliance Installer from other hosts on the same subnet as the appliance, you can't access it from hosts on other subnets. This condition should resolve itself within 15 minutes (when any ARP cache entries for the original controller time out), or you can clear the condition immediately by purging any old ARP cache entries manually from the local router or gateway.

.Steps

. Display the current configurations of the appliance and record them.
.. Log in to the appliance to be replaced:
  ... Enter the following command: `ssh admin@_grid_node_IP_`
  ... Enter the password listed in the `Passwords.txt` file.
  ... Enter the following command to switch to root: `su -`
  ... Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
.. Enter: `*run-host-command ipmitool lan print*` to display the current BMC configurations for the appliance.

. If the SG6100-CN controller is functioning sufficiently to allow for a controlled shutdown, link:power-sgf6112-off-on.html[shut down the SG6100-CN controller].

. If any of the network interfaces on this StorageGRID appliance are configured for DHCP, you might need to update the permanent DHCP lease assignments on the DHCP servers to reference the MAC addresses of the replacement appliance. The update ensures the appliance is assigned the expected IP addresses. 

. Remove and replace the SG6100-CN controller:
 .. Label and then disconnect the cables.
+
CAUTION: To prevent degraded performance, don't twist, fold, pinch, or step on the cables.

 .. Remove the failed controller from the cabinet or rack.
 .. Install the replacement controller into the cabinet or rack.
 .. Replace the cables.
 .. Power on the controller and monitor the controller LEDs.
. If the appliance you replaced had hardware drive encryption enabled for the SED drives, you must https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html#access-an-encrypted-drive[enter the drive encryption passphrase] to access the encrypted drives when the replacement appliance starts for the first time.
. If the appliance where you replaced the controller used a key management server (KMS) to encrypt data, additional configuration might be required before the node can join the grid. If the node does not automatically join the grid, make sure that these configuration settings have transferred to the new controller and manually configure any settings that don't have the expected configuration:
** link:../installconfig/configuring-network-links.html[Configure network links]
** link:../installconfig/setting-ip-configuration.html[Configure StorageGRID IP addresses]
** https://docs.netapp.com/us-en/storagegrid-118/admin/kms-overview-of-kms-and-appliance-configuration.html#set-up-the-appliance[Configure node encryption for the appliance^]

. Log in to the appliance with the replaced controller:
  .. Enter the following command: `ssh admin@_grid_node_IP_`
  .. Enter the password listed in the `Passwords.txt` file.
  .. Enter the following command to switch to root: `su -`
  .. Enter the password listed in the `Passwords.txt` file.
. Restore BMC network connectivity for the appliance. There are two options: 
* Use static IP, netmask, and gateway 
* Use DHCP to obtain an IP, netmask, and gateway

.. To restore the BMC configuration to use a static IP, netmask, and gateway, enter the following commands:
+
`*run-host-command ipmitool lan set 1 ipaddr _Appliance_IP_*`
+
`*run-host-command ipmitool lan set 1 netmask _Netmask_IP_*`
+
`*run-host-command ipmitool lan set 1 defgw ipaddr _Default_gateway_*`

.. To restore the BMC configuration to use DHCP to obtain an IP, netmask, and gateway, enter the following command: 
+
`*run-host-command ipmitool lan set 1 ipsrc dhcp*`

. After restoring BMC network connectivity, connect to the BMC interface to audit and restore any additional custom BMC configuration you might have applied. For example, you should confirm the settings for SNMP trap destinations and email notifications. See link:../installconfig/configuring-bmc-interface.html[Configure BMC interface].
. Confirm that the appliance node appears in the Grid Manager and that no alerts appear.

include::../_include/fru-statement.adoc[]


