---
permalink: sg6100/replace-cmos-in-sgf6112.html
sidebar: sidebar
keywords: storagegrid, sg6100, SGF6112, storage node, storage appliance, Replacing, replace, CMOS, battery
summary: 'Use this procedure to replace the CMOS coin cell battery on the system board.'
---
= Replace the CMOS battery in the SGF6112
:icons: font
:imagesdir: ../media/

[.lead]
Use this procedure to replace the CMOS coin cell battery on the system board.

Use these procedures to: 

* Remove the CMOS battery
* Reinstall the CMOS battery

== Remove the CMOS battery

.Before you begin

* You have verified that the CMOS battery in the SGF6112 needs to be replaced. 
+
link:verify-component-to-replace.html[Verify component to replace]
* You have physically located the SGF6112 appliance where you are replacing the CMOS battery in the data center.
+
link:locating-sgf6112-in-data-center.html[Locate appliance in data center]
+
NOTE: A link:power-sgf6112-off-on.html#shut-down-the-sgf6112-appliance[controlled shutdown of the appliance] is required before removing the appliance from the rack.

* You have disconnected all cables and removed the appliance cover.
+
link:reinstalling-sgf6112-cover.html[Remove SGF6112 cover]

include::../_include/2023-replace-cmos.adoc[]