---
permalink: sg6100/replace-nic-in-sgf6112.html
sidebar: sidebar
keywords: storagegrid, sg6100, storage node, storage appliance, Replacing, replace, NIC, network interface card
summary: 'You might need to replace a Network Interface Card \(NIC\) in the SGF6112 if it is not functioning optimally or if it has failed.'
---
= Replace internal NIC in the SGF6112 or SG6100-CN
:icons: font
:imagesdir: ../media/

[.lead]
You might need to replace an internal Network Interface Card (NIC) in the SGF6112 or SG6100-CN if it is not functioning optimally or if it has failed.

Use these procedures to: 

* Remove the NIC
* Reinstall the NIC

== Remove the internal NIC

.Before you begin

* You have the correct replacement NIC.
* You have determined the link:verify-component-to-replace.html[location of the NIC to replace].

* You have link:locating-sgf6112-in-data-center.html[physically located the SGF6112 appliance or SG6100-CN controller] where you are replacing the NIC in the data center.
+
NOTE: A link:power-sgf6112-off-on.html#shut-down-the-sgf6112-appliance[controlled shutdown of the appliance] is required before removing the appliance from the rack.

* You have disconnected all cables and link:reinstalling-sgf6112-cover.html[removed the appliance cover].

include::../_include/2023-replace-nic.adoc[]