---
permalink: sg6100/replace-controller-e4000-duplex.html
sidebar: sidebar
keywords: 
summary: 
---
= Replace E4000 storage controller (SG6160)
:icons: font
:imagesdir: ../media/

[.lead]
You might need to replace an E4000 controller  if it is not functioning optimally or if it has failed.

.Before you begin

* You have a replacement controller with the same part number as the controller you are replacing.
* You have labels to identify each cable that is connected to the controller.
* You have an ESD wristband, or you have taken other antistatic precautions.
* You have a #1 Phillips screwdriver.
* You have physically located the storage appliance where you are replacing the controller in the data center.

NOTE: Don't rely on the E-Series instructions to replace a controller in the StorageGRID appliance, because the procedures aren't the same.

.About this task

You can determine if you have a failed controller in two ways:

* A Grid Manager alert indicates a storage controller failure condition, and Grid Manager or the Recovery Guru in SANtricity System Manager direct you to replace the controller.
* The amber Attention LED on the controller is on, indicating that the controller has a fault.
+
NOTE: If both controllers in the shelf have their Attention LEDs on, contact technical support for assistance.

If your appliance contains two storage controllers, you can replace one of the controllers while your appliance is powered on and performing read/write operations, as long as the following conditions are true:

* The second controller in the shelf has Optimal status.
* The *OK to remove* field in the Details area of the Recovery Guru in SANtricity System Manager displays *Yes*, indicating that it is safe to remove this component.

NOTE: When possible, place the appliance into maintenance mode for this replacement procedure to minimize the potential impact of unforeseen errors or failures.

NOTE: If the second controller in the shelf does not have Optimal status or if the Recovery Guru indicates that it is not OK to remove the controller, contact technical support.


== Step 1: Prepare the replacement controller
Prepare the replacement E4000 controller.

.Steps
. Unpack the new controller, and set it on a flat, static-free surface.
+
Save the packing materials to use when shipping the failed controller.

. Locate the MAC address and FRU part number labels on the back of the replacement controller. 

== Step 2: Take the controller offline
Prepare to remove the failed controller and and take it offline. You can use SANtricity System Manager to perform these steps.

.Steps

. Confirm that the replacement part number for the failed controller is the same as the FRU part number for the replacement controller.
+
When a controller has a fault and needs to be replaced, the replacement part number is displayed in the Details area of the Recovery Guru. If you need to find this number manually, you can look on the *Base* tab for the controller.
+
CAUTION: *Possible loss of data access &#8212;* If the two part numbers aren't the same, don't attempt this procedure.

. Back up the configuration database.
+
If a problem occurs when you remove a controller, you can use the saved file to restore your configuration. The system will save the current state of the RAID configuration database, which includes all data for volume groups and disk pools on the controller.

.. Select *Support › Support Center › Diagnostics*.
.. Select *Collect Configuration Data*.
.. Click *Collect*.
+
The file is saved in the Downloads folder for your browser with the name, *configurationData-<arrayName>-<dateTime>.7z*.

. Collect support data for the appliance.
+
NOTE: Collecting support data before and after replacing a component ensures you can send a full set of logs to technical support if the replacement does not resolve the problem.
+
If a problem occurs when you remove a controller, you can use the saved file to troubleshoot the issue. The system will save inventory, status, and performance data about your storage array in a single file.

.. *Select Support › Support Center › Diagnostics*.
.. Select *Collect Support Data*.
.. Click *Collect*.


== Step 3: Remove controller canister

Remove a controller canister.

.Steps

. Put on an ESD wristband or take other antistatic precautions.
. Label each cable that is attached to the controller canister.
. Disconnect all the cables from the controller canister.
+
CAUTION: To prevent degraded performance, do not twist, fold, pinch, or step on the cables.

. Squeeze the latch on the cam handle until it releases, open the cam handle fully to release the controller canister from the midplane, and then, using two hands, pull the controller canister out of the chassis.
. Place the controller on a flat, static-free surface.


[[step4_replace_controller]]
== Step 4: Replace controller
Install the replacement controller and verify that it has rejoined the grid.

.Steps

. Install the replacement controller into the appliance.
 .. Turn the controller over, so that the removable cover faces down.
 .. With the cam handle in the open position, slide the controller all the way into the appliance.
 .. Move the cam handle to the left to lock the controller in place.
 .. Replace the cables.
 .. If the original controller used DHCP for the IP address, locate the MAC address on the label on the back of the replacement controller. Ask your network administrator to associate the DNS/network and IP address for the controller you removed with the MAC address for the replacement controller.
+
NOTE: If the original controller did not use DHCP for the IP address, the new controller will adopt the IP address of the controller you removed.
. Bring the controller online using SANtricity System Manager:
 .. Select *Hardware*.
 .. If the graphic shows the drives, select *Show back of controller*.
 .. Select the controller you want to place online.
 .. Select *Place Online* from the context menu, and confirm that you want to perform the operation.
. As the controller boots, check the controller LEDs.

** The amber Attention LED on the controller turns on and then turns off, unless there is an error.
** The Host Link LEDs might be on, blinking, or off, depending on the host interface.

. When the controller is back online, confirm that its status is Optimal and check the controller shelf's Attention LEDs.
+
If the status is not Optimal or if any of the Attention LEDs are on, confirm that all cables are correctly seated and the controller canister is installed correctly. If necessary, remove and reinstall the controller canister.
+
NOTE: If you cannot resolve the problem, contact technical support.
. If required, redistribute all volumes back to their preferred owner using SANtricity System Manager.
.. Select *Storage › Volumes*.
.. Select *More › Redistribute volumes*.
. Collect support data for your storage array using SANtricity System Manager.
.. Select *Support › Support Center › Diagnostics*.
.. Select *Collect Support Data*.
.. Click *Collect*.
+
The file is saved in the Downloads folder for your browser with the name, *support-data.7z*.

.What's next?
Your controller replacement is complete. You can resume normal operations.

include::../_include/fru-statement.adoc[] 

// 2024 FEB 26, SGRIDDOC-22