---
permalink: sg5700/troubleshoot-upgrading-drive-firmware-using-santricity-system-manager.html
sidebar: sidebar
keywords: storagegrid, sg5700, storage node, storage appliance, upgrade, upgrading, firmware, drive, disk, SANtricity System Manager, SANtricity
summary: 'You upgrade your drive firmware to make sure you have all the latest features and bug fixes.'
---
= Troubleshoot drive firmware upgrade errors
:icons: font
:imagesdir: ../media/

[.lead]
Troubleshoot errors that can occur during the upgrade of the firmware on the drives in your appliance using SANtricity System Manager.

* *Failed assigned drives*
+
One reason for the failure might be that the drive does not have the appropriate signature. Make sure that the affected drive is an authorized drive. Contact technical support for more information.
+
When replacing a drive, make sure that the replacement drive has a capacity equal to or greater than the failed drive you are replacing.
+
You can replace the failed drive while the storage array is receiving I/O.

* *Check storage array*
** Make sure that an IP address has been assigned to each controller.
** Make sure that all cables connected to the controller aren't damaged.
** Make sure that all cables are tightly connected.
* *Integrated hot spare drives*
+
This error condition must be corrected before you can upgrade the firmware.

* *Incomplete volume groups*
+
If one or more volume groups or disk pools are incomplete, you must correct this error condition before you can upgrade the firmware.

* *Exclusive operations (other than background media/parity scan) currently running on any volume groups*
+
If one or more exclusive operations are in progress, the operations must complete before the firmware can be upgraded. Use System Manager to monitor the progress of the operations.

* *Missing volumes*
+
You must correct the missing volume condition before the firmware can be upgraded.

* *Either controller in a state other than Optimal*
+
One of the storage array controllers needs attention. This condition must be corrected before the firmware can be upgraded.

* *Mismatched Storage Partition information between Controller Object Graphs*
+
An error occurred while validating the data on the controllers. Contact technical support to resolve this issue.

* *SPM Verify Database Controller check fails*
+
A storage partitions mapping database error occurred on a controller. Contact technical support to resolve this issue.

* *Configuration Database Validation (If supported by the storage array's controller version)*
+
A configuration database error occurred on a controller. Contact technical support to resolve this issue.

* *MEL Related Checks*
+
Contact technical support to resolve this issue.

* *More than 10 DDE Informational or Critical MEL events were reported in the last 7 days*
+
Contact technical support to resolve this issue.

* *More than 2 Page 2C Critical MEL Events were reported in the last 7 days*
+
Contact technical support to resolve this issue.

* *More than 2 Degraded Drive Channel Critical MEL events were reported in the last 7 days*
+
Contact technical support to resolve this issue.

* *More than 4 critical MEL entries in the last 7 days*
+
Contact technical support to resolve this issue.

// 2024 FEB 29, SGIRDDOC-52