---
permalink: commonhardware/considerations-and-requirements-for-appliance-node-cloning.html
sidebar: sidebar
keywords: storagegrid, clone appliance node, cloning appliance node
summary: 'Before cloning an appliance node, you must understand the considerations and requirements.'
---
= Considerations and requirements for appliance node cloning
:icons: font
:imagesdir: ../media/

[.lead]
Before cloning an appliance node, you must understand the considerations and requirements.

TIP: Node clone is disabled for Gateway Nodes. To replace a Gateway Node, decommission it and then perform an expansion to add a new appliance Gateway Node. The decommissioning and expansion procedure is much faster for a Gateway Node than for a Storage Node.

== Hardware requirements for the replacement appliance

Ensure that the replacement appliance meets the following criteria:

* The source node (appliance being replaced) and the target (new) appliance must be the same type of appliance:
** You can only clone an Admin Node appliance to a new services appliance.
** You can only clone a Storage Node appliance to a new storage appliance.
* For an Admin Node appliance, the source node appliance and the target appliance don't need to be the same appliance model; however, changing the appliance model might require replacing the cables or SFP modules.
+
For example, you can replace a SG1000 node appliance with a SG100 or replace a SG100 appliance with a SG1000 appliance.

* For Storage Node appliances, the source node appliance and the target appliance don't need to be the same type of appliance; however:
** The target appliance must have greater storage capacity than the source appliance.
+
For example, you can replace a SG5700 node appliance with a SG6000 appliance.
** The target appliance must have an equal or greater number of object storage volumes than the source appliance.
+
For example, you can't replace a SG6000 node appliance (16 object store volumes) with a SGF6112 appliance (12 object store volumes).

Contact your StorageGRID sales representative for help choosing compatible replacement appliances to clone specific appliance nodes in your StorageGRID installation.

== Prepare to clone an appliance node

You must have the following information before you clone an appliance node:

* Obtain a temporary IP address for the Grid Network from your network administrator for use with the target appliance during initial installation. If the source node belongs to an Admin Network or Client Network, obtain temporary IP addresses for these networks.
+
Temporary IP addresses are normally on the same subnet as the source node appliance being cloned and aren't needed after cloning completes. The source and target appliances must both connect to the primary Admin Node of your StorageGRID to establish a cloning connection.

* Determine which network to use for cloning data-transfer traffic that provides the best data-transfer performance without degrading StorageGRID network performance or data availability.
+
NOTE: Using the 1-GbE Admin Network for clone data transfer results in slower cloning.

* Determine if you'll use node encryption using a key management server (KMS) on the target appliance, so that you can enable node encryption during initial target appliance installation before cloning. You can check if node encryption is enabled on the source appliance node as described in the link:../installconfig/optional-enabling-node-encryption.html[enabling node encryption].
+
// 12.0
The source node and target appliance can have different node-encryption settings with the following exceptions. Node cloning is not supported from unencrypted-node sources to node-encrypted targets for the following appliances:
+
** An SGF6112 node appliance without node encryption to an SGF6112 appliance with node encryption 
** An SG1100 node appliance without node encryption to an SG1100 appliance with node encryption 
** An SG110 node appliance without node encryption to an SG110 appliance with node encryption

+
Data decryption and encryption is performed automatically during data transfer and when the target node restarts and joins the grid.

* Determine if the RAID mode on the target appliance should be changed from its default setting, so you can specify this information during initial target appliance installation before cloning. You can view information about the current RAID mode of the source appliance node on the *NODES* page in Grid Manager. Select the *Hardware* tab for the appliance.
+
The source node and target appliance can have different RAID settings.

* Plan for sufficient time to complete the node cloning process. Several days might be required to transfer data from an operational Storage Node to a target appliance. Schedule cloning at a time that minimizes the impact to your business.
* You should only clone one appliance node at a time. Cloning can prevent you from performing other StorageGRID maintenance functions at the same time.
* After you have cloned an appliance node, you can use the source appliance that was returned to a pre-install state as the target to clone another compatible node appliance.
